"""Blender headless: sculpt the floor 12 porcelain mask, export a compact mesh.

Run: blender -b --factory-startup --python tools/blender/build_concierge.py
The game keeps its animated eyes, hinged jaw and mouth collision anchor.
"""
import bpy
import math
import json
import base64
import struct
from pathlib import Path

bpy.ops.object.select_all(action='SELECT')
bpy.ops.object.delete(use_global=False)

def ellipsoid(name, at, scale, tilt=0):
    bpy.ops.mesh.primitive_uv_sphere_add(segments=48, ring_count=32, location=at)
    ob=bpy.context.object
    ob.name=name
    ob.scale=scale
    ob.rotation_euler[1]=tilt
    bpy.ops.object.transform_apply(location=False, rotation=False, scale=True)
    return ob

# Blender coordinates are deliberately the game's X/Y/Z; no import rotation.
parts=[ellipsoid('porcelain', (0,.58,.24), (3.19,3.18,2.96))]
for side in [-1,1]:
    parts.append(ellipsoid('cheek', (side*2.13,-.12,2.24), (.83,1.08,.62)))
    parts.append(ellipsoid('brow', (side*1.43,2.04,2.47), (1.14,.38,.65)))
parts.append(ellipsoid('nose_bridge',(0,.7,2.97),(.29,.91,.53)))
parts.append(ellipsoid('nose_tip',(0,.03,3.35),(.44,.37,.53)))
for side in [-1,1]:parts.append(ellipsoid('nose_wing',(side*.34,-.11,3.25),(.24,.22,.28)))
bpy.ops.object.select_all(action='DESELECT')
for p in parts:p.select_set(True)
bpy.context.view_layer.objects.active=parts[0]
bpy.ops.object.join()
mask=bpy.context.object
remesh=mask.modifiers.new('Sculpt union','REMESH')
remesh.mode='VOXEL';remesh.voxel_size=.065;remesh.use_smooth_shade=True
bpy.ops.object.modifier_apply(modifier=remesh.name)
smooth=mask.modifiers.new('Sculpt polish','SMOOTH');smooth.factor=.75;smooth.iterations=4
bpy.ops.object.modifier_apply(modifier=smooth.name)

def cut(cutter):
    bpy.context.view_layer.objects.active=mask
    mod=mask.modifiers.new('Carve','BOOLEAN');mod.operation='DIFFERENCE';mod.solver='EXACT';mod.object=cutter
    bpy.ops.object.modifier_apply(modifier=mod.name)
    bpy.data.objects.remove(cutter,do_unlink=True)

def box(at,scale):
    bpy.ops.mesh.primitive_cube_add(size=2,location=at)
    ob=bpy.context.object;ob.scale=scale
    bpy.ops.object.transform_apply(location=False,rotation=False,scale=True)
    return ob

# Keep only the forward mask. Cut clear sockets around the animated eyeballs.
cut(box((0,0,-3.2),(6,6,4.75)))
for side in [-1,1]:cut(ellipsoid('eye_cut',(side*1.55,1.15,3.18),(1.01,.71,2.1)))
# A rounded mouth arch, independent from the live mechanical jaw below it.
mouth=box((0,-2.45,3),(2.27,1.64,2.8))
bpy.context.view_layer.objects.active=mouth
bev=mouth.modifiers.new('Mouth corners','BEVEL');bev.width=.31;bev.segments=5
bpy.ops.object.modifier_apply(modifier=bev.name)
cut(mouth)
for side in [-1,1]:cut(ellipsoid('nostril',(side*.28,-.23,3.54),(.14,.10,.24)))
bpy.context.view_layer.objects.active=mask
dec=mask.modifiers.new('Mobile budget','DECIMATE');dec.ratio=.27
bpy.ops.object.modifier_apply(modifier=dec.name)
bev=mask.modifiers.new('Porcelain edge','BEVEL');bev.width=.045;bev.segments=2
bev.limit_method='ANGLE'
bpy.ops.object.modifier_apply(modifier=bev.name)
tri=mask.modifiers.new('Triangles','TRIANGULATE')
bpy.ops.object.modifier_apply(modifier=tri.name)
for p in mask.data.polygons:p.use_smooth=True

positions=[]
for vertex in mask.data.vertices:
    v=mask.matrix_world@vertex.co
    positions.extend(round(c*1000) for c in v)
indices=[v for p in mask.data.polygons for v in p.vertices]
assert len(mask.data.vertices)<65536
encode=lambda values,fmt:base64.b64encode(struct.pack('<'+fmt*len(values),*values)).decode()
target=Path(__file__).resolve().parents[2]/'src'/'f12ConciergeMesh.ts'
target.write_text('// Generated by tools/blender/build_concierge.py. Coordinates quantized to 1 mm.\n'
    + 'export const conciergeVertices = '+json.dumps(encode(positions,'h'))+';\n'
    + 'export const conciergeTriangles = '+json.dumps(encode(indices,'H'))+';\n')
print(json.dumps({'vertices':len(mask.data.vertices),'triangles':len(indices)//3,'bytes':target.stat().st_size,'output':str(target)}))
