// build-wasm.mjs — compile Floor 7's C + hand-written assembly to WebAssembly
// and embed the bytes as base64 in a committed TS module, so the production
// build (which has no clang) just decodes + instantiates. Re-run this whenever
// floor7.c / floor7_asm.s change:  node wasm/build-wasm.mjs
import { execSync } from 'node:child_process';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const dir = path.dirname(fileURLToPath(import.meta.url));
const wasmOut = path.join(dir, 'floor7.wasm');
const tsOut = path.join(dir, '..', 'src', 'floor7-wasm.ts');

const cmd = [
    'clang', '--target=wasm32', '-nostdlib', '-O2',
    '-Wl,--no-entry', '-Wl,--export-dynamic', '-Wl,--allow-undefined',
    '-o', wasmOut,
    path.join(dir, 'floor7.c'), path.join(dir, 'floor7_asm.s'),
].join(' ');

console.log('> ' + cmd);
execSync(cmd, { stdio: 'inherit' });

const bytes = fs.readFileSync(wasmOut);
const b64 = bytes.toString('base64');
const ts = `// AUTO-GENERATED by wasm/build-wasm.mjs — DO NOT EDIT BY HAND.
// Floor 7's brain (floor7.c + floor7_asm.s) compiled to WebAssembly, base64 so
// the single-file build inlines it (no .wasm fetch). Size: ${bytes.length} bytes.
export const FLOOR7_WASM_B64 = "${b64}";

export function decodeFloor7Wasm(): Uint8Array {
    const bin = atob(FLOOR7_WASM_B64);
    const out = new Uint8Array(bin.length);
    for (let i = 0; i < bin.length; i++) out[i] = bin.charCodeAt(i);
    return out;
}
`;
fs.writeFileSync(tsOut, ts);
console.log(`wrote ${tsOut} (${bytes.length} bytes wasm -> ${b64.length} b64 chars)`);
