// build-wasm.mjs — compile Floor 7's C + hand-written assembly to WebAssembly
// and embed the bytes as base64 in a committed TS module, so the production
// build (which has no clang) just decodes + instantiates. Re-run this whenever
// floor7.c / floor7_asm.s change:  node wasm/build-wasm.mjs
import { execSync } from 'node:child_process';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const dir = path.dirname(fileURLToPath(import.meta.url));
const wasmOut = path.join(dir, 'floor7.wasm');
const tsOut = path.join(dir, '..', 'src', 'floor7-wasm.ts');

// Compile C + hand-written assembly + C++ each to a wasm object, then link.
const o = (f) => path.join(dir, f);
const steps = [
    `clang --target=wasm32 -nostdlib -O2 -c ${o('floor7.c')} -o ${o('floor7.o')}`,
    `clang --target=wasm32 -nostdlib -O2 -c ${o('floor7_asm.s')} -o ${o('floor7_asm.o')}`,
    `clang++ --target=wasm32 -nostdlib -O2 -fno-exceptions -fno-rtti -c ${o('floor7_geo.cpp')} -o ${o('floor7_geo.o')}`,
    `clang --target=wasm32 -nostdlib -Wl,--no-entry -Wl,--export-dynamic -Wl,--allow-undefined -o ${wasmOut} ${o('floor7.o')} ${o('floor7_asm.o')} ${o('floor7_geo.o')}`,
];
for (const cmd of steps) { console.log('> ' + cmd); execSync(cmd, { stdio: 'inherit' }); }
for (const f of ['floor7.o', 'floor7_asm.o', 'floor7_geo.o']) { try { fs.unlinkSync(o(f)); } catch (e) { /* ignore */ } }

const bytes = fs.readFileSync(wasmOut);
const b64 = bytes.toString('base64');
const ts = `// AUTO-GENERATED by wasm/build-wasm.mjs — DO NOT EDIT BY HAND.
// Floor 7's brain (floor7.c + floor7_asm.s) compiled to WebAssembly, base64 so
// the single-file build inlines it (no .wasm fetch). Size: ${bytes.length} bytes.
export const FLOOR7_WASM_B64 = "${b64}";

export function decodeFloor7Wasm(): Uint8Array {
    const bin = atob(FLOOR7_WASM_B64);
    const out = new Uint8Array(bin.length);
    for (let i = 0; i < bin.length; i++) out[i] = bin.charCodeAt(i);
    return out;
}
`;
fs.writeFileSync(tsOut, ts);
console.log(`wrote ${tsOut} (${bytes.length} bytes wasm -> ${b64.length} b64 chars)`);
